### ISSUE TITLE
multiple accounts

### ISSUE THREAD

**Issue by renejorissen** [michaelrosejr/arubasso#1]
Question: 
I would like to add a domain claim to multiple accounts, like 10 different accounts. I created the hpe_css_attribute claim in Azure and I am able to put the claim for 2 accounts in one Attribute rule, like shown below.

`version_1#ba4baee685561123bb2e9a52317d7d71:00000000-0000-0000-0000-000000000000:Account Administrator:ALL_SCOPES:f3a3e40f123123455d6ebefa1e66d:Aruba Central Administrator:ALL_SCOPES#d284b2267ab12abecd703e7cfd568923:00000000-0000-0000-0000-000000000000:Account Administrator:ALL_SCOPES:2e87b15b08124aebceb1fa9336fd7:Aruba Central Administrator:ALL_SCOPES`

The problem starts by adding a third account. It looks like I hit the maximum character size of the claim. I tried to another Attribute rule, but that is no option either. I receive the error message: "Duplicate condition"

**Comment by renejorissen** [comment]
I managed to get this issue fixed, but using dedicated hpe_css_attribute claims per account, like hpe_css_attribute_account01 and hpe_css_attribute_account02.

**Comment by michaelrosejr** [comment]
I was aware of the limit but havent run across a customer that needed more than 1024. Good to know and thanks for sharing!
